### PR TITLE
Add some utilities to the playground

### PR DESCRIPTION
**Pull request by alanz**
As a new user, being told variables area available does not really help
much, and it helps to be able to inspect them, somehow.

This is a feeble start on that, and as much to prompt discussion as anything else.

### CODE REVIEW

**Comment by alanz** [comment]
I actually think it would be useful to render the `mold-data` directly into the commented area in the Playground.

**Comment by ag91** [comment]
I really resonate with this: state should be visible.
How does it look for very big self and mold-data (CodeAsTree creates big self on average because it tokenizes source code)? I am just slightly worried it will fill the buffer: should we trim?

**Comment by alanz** [comment]
I was thinking about this a bit.  I think `self` is the only one with a size problem, so maybe not show it by default, blank it out or some such.
It would be great to have something like a common-lisp inspector view where you can click on a field to see more detail.

And maybe a poor person's substitute would be to make the playground an org file, with clickable links in it.

**Comment by ag91** [comment]
Uhm, what do you think about this project? https://github.com/mmontone/emacs-inspector

https://user-images.githubusercontent.com/6580039/143928686-e94109a5-a5fc-43a4-bab6-4edcf69f8471.mp4

**Comment by alanz** [comment]
That looks pretty useful

**Comment by ag91** [comment]
I am still thinking about this: I wonder if we should work more on the presentation.
It could be interesting to split the screen and present an inspector of your current context all the time your cursor is on a mold. 
Like here:
screen-2021-12-02-21-42-13

**Comment by alanz** [comment]
Looks good. Better than the prior one.

**Comment by ag91** [comment]
Okay, finally I got to something that satisfies me:
screen-2021-12-26-18-19-16

I changed the UI to store your original windows configuration and always display the original buffer and the final mold (no matter how many composite molds you implicitly invoked). This also shows an inspector that shows the values of self and mold-data.

Could you let me know if that feels good? If so we could close this PR ;)

**Comment by alanz** [comment]
Sorry for the late reply, time of year and all that.

Yes, it does look good. I could not find the code for your version on your branch, is it available somewhere?

Otherwise merge it, it is a step in the right direction.

**Comment by alanz** [comment]
nvm, I see it is already on master. And works great.

**Pull request closed without merging**
